#!/usr/bin/env python3
"""Derives the two icon SVGs from a piece of the site's own artwork.

    assets/svg/icon.svg      the whole animal, for the iOS touch icon and the
                             48px favicon entry
    assets/svg/icon-tab.svg  head and shoulders, for the 16 and 32px entries
                             and for the <link rel="icon"> SVG

Two variants because the art is a 152x100 landscape drawing: fit whole into a
16px square it becomes about 12x8 device pixels and the face disappears. The
tighter crop spends those same pixels on the head instead. Browsers pick the
right entry out of the .ico themselves, and the SVG link points at the tab
variant since that is the size it actually gets drawn at.

Run tools/build-icons.sh, which calls this and then rasterises the results.
"""

import pathlib

ART = "assets/svg/cat-bubu.svg"
ART_VIEWBOX = (152.0, 100.0)

# x, y, w, h in the artwork's own coordinates. Square, so it maps to the tile
# without distortion. Ears top out around y=19 and the ruff runs to y=68, so
# this holds the whole head with a little of the white chest under it.
HEAD_CROP = (10, 15, 48, 48)

SIZE = 512      # master render size; everything is downsampled from here
INSET = 32      # padding around the head crop
FULL_WIDTH = 400

# Just the art on the site's paper colour — no border, no badge. The ground is
# opaque rather than transparent because iOS composites any alpha in a touch
# icon against black, which would ring the drawing in a dark halo.
GROUND = "#FDFAE0"

NOTE = """<!-- Generated by tools/make-icon-svgs.py from {art} — edit that, not this.

     Full-bleed and square on purpose: iOS applies its own rounded mask to the
     touch icon, so corners baked in here would be clipped twice. The ground is
     opaque so the mark holds up on a dark tab strip as well as a light one.

     Two changes come from the source art. fill="none" is carried over from its
     root element — many paths are outlines that set only a stroke, and without
     it they inherit the default fill and come out solid black.
     vector-effect="non-scaling-stroke" is dropped so the linework thickens with
     the mark; left in, it pins strokes to device pixels and the drawing renders
     as hairlines at icon sizes. -->"""


def load_art(root: pathlib.Path) -> str:
    src = (root / ART).read_text()
    inner = src[src.index(">", src.index("<svg")) + 1 : src.rindex("</svg>")]
    return inner.replace(' vector-effect="non-scaling-stroke"', "")


def tile(inner: str, x: float, y: float, w: float, h: float, viewbox: str) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" aria-label="Rahman &amp; Fia">
{NOTE.format(art=ART)}
<rect width="{SIZE}" height="{SIZE}" fill="{GROUND}"/>
<svg x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" viewBox="{viewbox}" fill="none">{inner}</svg>
</svg>
"""


def main() -> None:
    root = pathlib.Path(__file__).resolve().parent.parent
    inner = load_art(root)

    vw, vh = ART_VIEWBOX
    fw = FULL_WIDTH
    fh = fw * vh / vw
    full = tile(inner, (SIZE - fw) / 2, (SIZE - fh) / 2, fw, fh, f"0 0 {vw:g} {vh:g}")

    m = SIZE - 2 * INSET
    cx, cy, cw, ch = HEAD_CROP
    head = tile(inner, INSET, INSET, m, m, f"{cx} {cy} {cw} {ch}")

    for name, body in (("icon.svg", full), ("icon-tab.svg", head)):
        path = root / "assets" / "svg" / name
        path.write_text(body)
        print(f"make-icon-svgs: wrote assets/svg/{name}")


if __name__ == "__main__":
    main()
